export type Grade = {
    courseCode:string,
    courseName: string,
    numberOfHours:number,
    grade: number
}

export const c: Grade[][] = [

    [{
        courseCode:"CSE111",
        courseName:"DataBase",
        numberOfHours:17,
        grade:4
    },
    {
        courseCode:"CSE121",
        courseName:"Software",
        numberOfHours:17,
        grade:3.4
    },
    {
        courseCode:"CSE131",
        courseName:"Math1",
        numberOfHours:17,
        grade:3.5
    },
    {
        courseCode:"CSE211",
        courseName:"Math2",
        numberOfHours:17,
        grade:3.9
    },
    {
        courseCode:"CSE331",
        courseName:"Networks",
        numberOfHours:17,
        grade:3.7
    },
    {
        courseCode:"CSE221",
        courseName:"Math5",
        numberOfHours:17,
        grade:3.5
    }],

    [{
        courseCode:"CSE111",
        courseName:"DataBase",
        numberOfHours:17,
        grade:4
    },
    {
        courseCode:"CSE121",
        courseName:"Software",
        numberOfHours:17,
        grade:3.4
    },
    {
        courseCode:"CSE131",
        courseName:"Math1",
        numberOfHours:17,
        grade:3.5
    },
    {
        courseCode:"CSE211",
        courseName:"Math2",
        numberOfHours:17,
        grade:3.9
    },
    {
        courseCode:"CSE331",
        courseName:"Networks",
        numberOfHours:17,
        grade:3.7
    },
    {
        courseCode:"CSE221",
        courseName:"Math5",
        numberOfHours:17,
        grade:3.5
    }],
    
    [{
        courseCode:"CSE111",
        courseName:"DataBase",
        numberOfHours:17,
        grade:4
    },
    {
        courseCode:"CSE121",
        courseName:"Software",
        numberOfHours:17,
        grade:3.4
    },
    {
        courseCode:"CSE131",
        courseName:"Math1",
        numberOfHours:17,
        grade:3.5
    },
    {
        courseCode:"CSE211",
        courseName:"Math2",
        numberOfHours:17,
        grade:3.9
    },
    {
        courseCode:"CSE331",
        courseName:"Networks",
        numberOfHours:17,
        grade:3.7
    },
    {
        courseCode:"CSE221",
        courseName:"Math5",
        numberOfHours:17,
        grade:3.5
    }]
]