server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: marwan1234#
    url: jdbc:mysql://localhost:3306/central-student-hub
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true